---
- name: Deploy APIC model
  hosts: apic
  gather_facts: no
  vars:
    apic_snapshot: True
    apic_deploy: True
    apic_option_render: False
    apic_option_configure: True
    apic_option_delete: True

  tasks:
    - name: APIC Snapshot
      include_role:
        name: cisco.aac.apic_snapshot
      when: apic_snapshot

    - name: APIC Deploy
      include_role:
        name: cisco.aac.apic_deploy
      when: apic_deploy
